export const invoiceData = [
  {
    id: 1,
    date: "jan",
    title: "Dev",
    billTo: "xyz",
    status: "unpaid",
    tax: 0,
    amount: 1000,
  },
  {
    id: 2,
    date: "feb",
    title: "Dev",
    billTo: "zym",
    status: "unpaid",
    tax: 0,
    amount: 1500,
  },
  {
    id: 3,
    date: "mar",
    title: "Web Dev",
    billTo: "xyz",
    status: "paid",
    tax: 0,
    amount: 1800,
  },
  {
    id: 4,
    date: "apr",
    title: "Dev",
    billTo: "zym",
    status: "overdue",
    tax: 0,
    amount: 1100,
  },
  {
    id: 5,
    date: "dec",
    title: "Dev",
    billTo: "xyz",
    status: "paid",
    tax: 0,
    amount: 1000,
  },
  {
    id: 6,
    date: "jun",
    title: "Dev",
    billTo: "zym",
    status: "unpaid",
    tax: 0,
    amount: 1500,
  },
  {
    id: 7,
    date: "apr",
    title: "Web Dev",
    billTo: "xyz",
    status: "paid",
    tax: 0,
    amount: 1800,
  },
  {
    id: 8,
    date: "may",
    title: "Dev",
    billTo: "zym",
    status: "overdue",
    tax: 0,
    amount: 1100,
  },
  {
    id: 9,
    date: "jan",
    title: "Dev",
    billTo: "xyz",
    status: "paid",
    tax: 0,
    amount: 1000,
  },
  {
    id: 10,
    date: "jul",
    title: "Dev",
    billTo: "zym",
    status: "unpaid",
    tax: 0,
    amount: 1500,
  },
  {
    id: 11,
    date: "aug",
    title: "Web Dev",
    billTo: "xyz",
    status: "paid",
    tax: 0,
    amount: 1800,
  },
  {
    id: 12,
    date: "dec",
    title: "Dev",
    billTo: "zym",
    status: "overdue",
    tax: 0,
    amount: 1100,
  },
  {
    id: 13,
    date: "nov",
    title: "Dev",
    billTo: "xyz",
    status: "paid",
    tax: 0,
    amount: 1000,
  },
  {
    id: 14,
    date: "may",
    title: "Dev",
    billTo: "zym",
    status: "unpaid",
    tax: 0,
    amount: 1500,
  },
  {
    id: 15,
    date: "jun",
    title: "Web Dev",
    billTo: "xyz",
    status: "paid",
    tax: 0,
    amount: 1800,
  },
  {
    id: 16,
    date: "jul",
    title: "Dev",
    billTo: "zym",
    status: "overdue",
    tax: 0,
    amount: 1100,
  },
];
